# Generated by Django 3.0.2 on 2020-01-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0004_auto_20200123_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('delivered_datetime', models.DateTimeField(default=None, null=True)),
                ('delivery_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kart.DeliveryAgent')),
                ('shopping_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kart.ShoppingUser')),
            ],
        ),
    ]
