# Generated by Django 3.0.2 on 2020-01-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0007_auto_20200124_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
    ]
