# Generated by Django 3.0.2 on 2020-01-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0012_auto_20200124_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='resolved',
            new_name='is_resolved',
        ),
    ]
